front_index:
    path: /
    defaults: { _controller: KoreFrontBundle:Front:index }

front_product:
    path: /product
    defaults: { _controller: KoreFrontBundle:Front:product }

front_login:
    path:     /login
    defaults: { _controller: "KoreFrontBundle:Security:login" }
    methods:  [GET, POST]

front_logout:
    path: /logout