liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        resource_photography_small:
            quality: 75
            filters:
                upscale: { min: [160, 100] }
                thumbnail: { size: [160, 100], mode: outbound }
        resource_photography_medium:
            quality: 75
            filters:
                upscale: { min: [640, 400] }
                thumbnail: { size: [640, 400], mode: outbound }
        resource_photography_large:
            quality: 75
            filters:
                upscale: { min: [1600, 1000] }
                thumbnail: { size: [1600, 1000], mode: outbound }
        brand_medium: ~
