kore_admin:
    resource: "@KoreAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

kore_front:
    resource: "@KoreFrontBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
