kore_admin:
    resource: "@KoreAdminBundle/Resources/config/routing.yml"
    prefix:   /kore/admin

kore_page:
    resource: "@KorePageBundle/Resources/config/routing.yml"
    prefix:   /kore/page

kore_front:
    resource: "@KoreFrontBundle/Resources/config/routing.yml"
    prefix:   /
