# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    root: { password: %root_password%, roles: 'ROLE_USER' }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:   ^/
            anonymous: true
            form_login:
                login_path: /login
                failure_path: /login
                check_path: /login
                always_use_default_target_path: true
                default_target_path: /admin/productgroup
                csrf_token_generator: security.csrf.token_manager
                failure_path: /login
            logout:
                path:   /logout
                target: /


    access_control:
        - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/admin, roles: [ROLE_USER] }
        - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
