admin_feature_index:
    path:     /
    defaults: { _controller: "KoreAdminBundle:Feature:index" }
    methods:  GET

admin_feature_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAdminBundle:Feature:show" }
    methods:  GET

admin_feature_new:
    path:     /new
    defaults: { _controller: "KoreAdminBundle:Feature:new" }
    methods:  [GET, POST]

admin_feature_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAdminBundle:Feature:edit" }
    methods:  [GET, POST]

admin_feature_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAdminBundle:Feature:delete" }
    methods:  DELETE
