admin_frontpagephoto_index:
    path:     /
    defaults: { _controller: "KoreAdminBundle:FrontpagePhoto:index" }
    methods:  GET

admin_frontpagephoto_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAdminBundle:FrontpagePhoto:show" }
    methods:  GET

admin_frontpagephoto_new:
    path:     /new
    defaults: { _controller: "KoreAdminBundle:FrontpagePhoto:new" }
    methods:  [GET, POST]

admin_frontpagephoto_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAdminBundle:FrontpagePhoto:edit" }
    methods:  [GET, POST]

admin_frontpagephoto_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAdminBundle:FrontpagePhoto:delete" }
    methods:  DELETE
