admin_frontpage_index:
    path:     /
    defaults: { _controller: "KoreAdminBundle:Frontpage:index" }
    methods:  GET

admin_frontpage_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAdminBundle:Frontpage:show" }
    methods:  GET

admin_frontpage_new:
    path:     /new
    defaults: { _controller: "KoreAdminBundle:Frontpage:new" }
    methods:  [GET, POST]

admin_frontpage_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAdminBundle:Frontpage:edit" }
    methods:  [GET, POST]

admin_frontpage_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAdminBundle:Frontpage:delete" }
    methods:  DELETE
