Kore\AdminBundle\Entity\ProductGroup:
    type: entity
    table: ProductGroup
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        products:
            targetEntity: Kore\AdminBundle\Entity\Product
            mappedBy: productgroup
            cascade: ['persist']
    fields:
        name:
            type: string
            length: 300
            nullable: true
        description:
            type: text
            nullable: true
        imagename:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }