Kore\AdminBundle\Entity\Product:
    type: entity
    table: Product
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        productgroup:
            targetEntity: Kore\AdminBundle\Entity\ProductGroup
            inversedBy: products
    fields:
        name:
            type: string
            length: 300
            nullable: true
        description:
            type: text
            nullable: true
        price:
            type: integer
        reference:
            type: string
            length: 1
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }