kore_admin_product:
    resource: "@KoreAdminBundle/Resources/config/routing/product.yml"
    prefix:   /product

kore_admin_productgroup:
    resource: "@KoreAdminBundle/Resources/config/routing/productgroup.yml"
    prefix:   /productgroup

kore_admin_feature:
    resource: "@KoreAdminBundle/Resources/config/routing/feature.yml"
    prefix:   /feature

kore_admin_contact:
    resource: "@KoreAdminBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

kore_admin_brand:
    resource: "@KoreAdminBundle/Resources/config/routing/brand.yml"
    prefix:   /brand

kore_admin_header:
    resource: "@KoreAdminBundle/Resources/config/routing/header.yml"
    prefix:   /header

kore_admin_photography:
    resource: "@KoreAdminBundle/Resources/config/routing/photography.yml"
    prefix:   /photography
